/*!CK:2102170212!*//*1375709742,178146351*/

if (self.CavalryLogger) { CavalryLogger.start_js(["UHkMp"]); }

__d("AdblockDetector",["CSS"],function(a,b,c,d,e,f){var g=b('CSS'),h='data-adblock-hash',i={},j=0;function k(l,m){var n=l.getAttribute(h);if(!n){n=++j;l.setAttribute(h,n);}else if(i[n]){clearTimeout(i[n]);i[n]=null;}i[n]=setTimeout(function(){i[n]=null;if(!l.offsetHeight){var o=l,p=document.getElementsByTagName('body')[0];while(o&&o!==p){if(!o.style||g.hasClass(o,'hidden_elem')||o.style.display==='none'||o.style.height==='0px'||o.style.height===0||o.style.height==='0'||o.childNodes.length===0)return;o=o.parentNode;}if(o===p)m&&m(l);}},3000);}f.assertUnblocked=k;});
__d("AdblockDetectorLogging",["AdblockDetector","EagleEye"],function(a,b,c,d,e,f){var g=b('AdblockDetector'),h=b('EagleEye');function i(j){g.assertUnblocked(j,h.log.bind(h,'ads',{event:'ads_blocked'}));}f.assertUnblocked=i;});
__d("EmuController",["AsyncRequest","DataStore","URI","copyProperties","emptyFunction","ge","goURI"],function(a,b,c,d,e,f){var g=b('AsyncRequest'),h=b('DataStore'),i=b('URI'),j=b('copyProperties'),k=b('emptyFunction'),l=b('ge'),m=b('goURI');function n(o,p){var q=l(o);if(!q)return null;this.impression=p;this.containerId=o;h.set(q,'emuController',this);return this;}j(n,{fromContainer:function(o){var p=l(o);if(!p)return null;return h.get(p,'emuController');},getEventClass:function(o){return "emuEvent"+String(o).trim();}});j(n.prototype,{EVENT_HANDLER_PATH:'/ajax/emu/end.php',CLICK:1,FAN:"fad_fan",event:function(o,p,q,r){var s={eid:this.impression,f:0,ui:this.containerId,en:o,a:1};if(p)s.ed=JSON.stringify(p);if(!r)r=k;var t=new g().setURI(this.EVENT_HANDLER_PATH).setData(s).setErrorHandler(r);if(q)t.setHandler(q);t.send();},redirect:function(){var o={eid:this.impression,f:0,ui:this.containerId,en:this.CLICK,a:0,sig:Math.floor(Math.random()*65535)+65536},p=new i(this.EVENT_HANDLER_PATH);p.setQueryData(o);m(p);}});e.exports=n;});
__d("legacy:ad-units-base-js",["EmuController"],function(a,b,c,d){a.EmuController=b('EmuController');},3);
__d("BassWhitespaceListener",["Bootloader","Event","Parent","copyProperties","goURI"],function(a,b,c,d,e,f){var g=b('Bootloader'),h=b('Event'),i=b('Parent'),j=b('copyProperties'),k=b('goURI');function l(m,n){this.link=n;h.listen(m,'click',this.onclicked.bind(this));}j(l.prototype,{onclicked:function(m){if(i.byTag(m.getTarget(),'A'))return;switch(this.link.getAttribute('rel')){case 'async':g.loadModules(['AsyncRequest'],function(o){o.bootstrap(this.link.getAttribute('ajaxify'),this.link);}.bind(this));break;case 'theater':var n=i.byClass(m.getTarget(),'fbPhotoSnowlift');g.loadModules(['PhotoViewer'],function(o){o.bootstrap(this.link.getAttribute('ajaxify'),this.link);}.bind(this));if(n)return false;break;default:k(this.link.getAttribute('href'));}}});e.exports=l;});
__d("legacy:ad-units-stream-whitespace",["BassWhitespaceListener"],function(a,b,c,d){a.BassWhitespaceListener=b('BassWhitespaceListener');},3);
__d("AppRequestReminders",["AsyncRequest","CSS","DOM","ge"],function(a,b,c,d,e,f){var g=b('AsyncRequest'),h=b('CSS'),i=b('DOM'),j=b('ge'),k=0,l={},m=1,n=j('OtherAppReqReminder'),o=function(u,v,w){l[v]={node:u,seq:m++,reqCount:w};},p=function(u){k=u;},q=function(u){return u.id.split('_')[1];},r=function(u){var v=j(u),w=v.nextSibling;if(w!==n){h.show(w);k-=l[q(w)].reqCount;}s(k);},s=function(u){new g().setURI('/ajax/reminders/update_count.php').setData({new_count:u}).setMethod('POST').send();},t=function(u,v){if(n&&v&&u>0){i.setContent(j('OtherAppReqLabel'),v);}else if(n){h.hide(n);}else h.hide(j('OtherAppReqReminder'));};f.initNode=o;f.handleRemove=r;f.updateCount=t;f.setTotalOtherCount=p;});
__d("legacy:async-signal",["AsyncSignal"],function(a,b,c,d){a.AsyncSignal=b('AsyncSignal');},3);
__d("NetEgo",["Arbiter","CSS","DOM","URI","ge","Animation"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('CSS'),i=b('DOM'),j=b('URI'),k=b('ge'),l=b('Animation'),m={setup:function(n){g.subscribe(['page/liked','FriendRequest/sending'],function(o,p){if(n==p.id||n==p.uid){var q=k(document.body,'.ego_unit_container');if(q){var r=i.scry(q,'.ego_unit'),s=r.length;for(var t=0;t<s;t++){var u=r[t].getAttribute('data-ego-fbid');if(u==p.id||u==p.uid){var v=i.find(r[t],'.ego_action a');if(v)v.click();break;}}}}});},updateXids:function(n,o){if(n.length==0&&o.length==0)return;var p=function(z){return function(aa){var ba=aa.getAttribute(z);if(!ba)return false;var ca=new j(ba).getQueryData();return !!ca.xids;};},q=i.scry(document.body,'.ego_unit a');q=q.filter(p('ajaxify'));if(q.length==0)return;var r=new j(q[0].getAttribute('ajaxify')),s=r.getQueryData();if(!s.xids)return;try{var u=JSON.parse(s.xids);}catch(t){return;}for(var v=0;v<n.length;++v)delete u[n[v]];for(v=0;v<o.length;++v)u[o[v]]=1;var w=JSON.stringify(u),x=function(z,aa){r=new j(z.getAttribute(aa));s=r.getQueryData();s.xids=w;r.setQueryData(s);z.setAttribute(aa,r.toString());};for(v=0;v<q.length;++v)x(q[v],'ajaxify');var y=i.scry(document.body,'.ego_unit form');y=y.filter(p('action'));for(v=0;v<y.length;++v)x(y[v],'action');},replaceUnit:function(n,o,p,q){var r=i.insertAfter(n,o);r.forEach(h.hide);if(q!==undefined&&q!==null){(function(){m._replaceUnitFadeout(n,r,p);}).defer(q);}else m._replaceUnitFadeout(n,r,p);},_replaceUnitFadeout:function(n,o,p){if(p){new l(n).from('opacity',1).to('opacity',0).duration(p).checkpoint(1,function(){m._replaceUnitElement(n,o);}).go();}else m._replaceUnitElement(n,o);},_replaceUnitElement:function(n,o){i.remove(n);o.forEach(h.show);g.inform('netego_replacedUnit');m.clearHeader();},clearHeader:function(){var n=i.scry(document.body,'.ego_column'),o=[];for(var p=0;p<n.length;++p)o=o.concat(i.scry(n[p],'.uiHeader'));for(p=0;p<o.length;++p){var q=o[p].nextSibling;if(!q||q.childNodes.length===0){i.remove(o[p]);}else if(q.childNodes.length===1){var r=q.childNodes[0];if(h.hasClass(r,'ego_appended_units')&&r.childNodes.length===0)i.remove(o[p]);}}}};e.exports=m;});
__d("LoadRecommendations",["Event","AsyncRequest"],function(a,b,c,d,e,f){var g=b('Event'),h=b('AsyncRequest'),i={loadOnClick:function(j){g.listen(j,'click',function(){new h().setURI('/ajax/pages/reminder/recommendations').send();});}};e.exports=i;});
__d("ReminderStory",["AsyncRequest","endsWith","Event","DOMQuery","ScrollableArea"],function(a,b,c,d,e,f){var g=b('AsyncRequest'),h=b('endsWith'),i=b('Event'),j=b('DOMQuery'),k=b('ScrollableArea');function l(m,n,o){i.listen(m,'click',function(p){n.show();if(o){var q={context_data:o};new g().setURI('/growth/reminder/logging.php').setData(q).send();}});n.subscribe('aftershow',function(){var p=n.getRoot(),q=j.find(p,'#SuggestBelowInvite');if(q)new g().setURI('/ajax/pages/reminder/recommendations').send();});n.subscribe('aftershow',function(){var p=n.getRoot(),q=j.scry(p,'.inlineReplyTextArea');if(q.length>0)q[0].focus();var r=j.scry(p,'.jewelItemNew'),s=[];for(var t in r){var u=r[t].getAttribute('id');if(u&&h(u,'_1_req'))s=s.concat(u.replace('_1_req',''));}if(s.length>0)new g().setURI('/friends/requests/log_impressions').setData({ids:s.join(','),ref:'reminder_box'}).send();k.poke(j.scry(p,'.uiScrollableArea')[0]);});}e.exports=l;});